#!/bin/bash

clear
javac -d . -cp lib/* PrimeFactors.java && \
  java -cp .:lib/* org.junit.runner.JUnitCore com.pillartechnology.practice.PrimeFactors 2>&1 | \
    grep -v "at org.junit" | \
    grep -v "at sun.reflect" | \
    grep -v "java.lang"
echo
echo

